#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run tests of energy consumption in the example implementations
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        cmd=""
        tag=""

        case "${1}" in 
          "--stm")
            cmd="testOnly *STMSpec"
            tag="stm"
            ;;

          "--yolo")
            cmd="testOnly *YOLOSpec"
            tag="yolo"
            ;;
        esac;

        for run in {1..100}; do
            sbt "set energyMonitorPersistenceTag := Some(\"${tag}\");energyMonitorPreSample;kvStore/${cmd};energyMonitorPostSampleHttp";
        done;
    fi
fi

